// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: balances/grpc/balances.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BalancesService_CurrentOne_FullMethodName = "/grpc.BalancesService/CurrentOne"
)

// BalancesServiceClient is the client API for BalancesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BalancesServiceClient interface {
	CurrentOne(ctx context.Context, in *GetCurrentOneRequest, opts ...grpc.CallOption) (*GetCurrentOneResponse, error)
}

type balancesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBalancesServiceClient(cc grpc.ClientConnInterface) BalancesServiceClient {
	return &balancesServiceClient{cc}
}

func (c *balancesServiceClient) CurrentOne(ctx context.Context, in *GetCurrentOneRequest, opts ...grpc.CallOption) (*GetCurrentOneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCurrentOneResponse)
	err := c.cc.Invoke(ctx, BalancesService_CurrentOne_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BalancesServiceServer is the server API for BalancesService service.
// All implementations must embed UnimplementedBalancesServiceServer
// for forward compatibility.
type BalancesServiceServer interface {
	CurrentOne(context.Context, *GetCurrentOneRequest) (*GetCurrentOneResponse, error)
	mustEmbedUnimplementedBalancesServiceServer()
}

// UnimplementedBalancesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBalancesServiceServer struct{}

func (UnimplementedBalancesServiceServer) CurrentOne(context.Context, *GetCurrentOneRequest) (*GetCurrentOneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CurrentOne not implemented")
}
func (UnimplementedBalancesServiceServer) mustEmbedUnimplementedBalancesServiceServer() {}
func (UnimplementedBalancesServiceServer) testEmbeddedByValue()                         {}

// UnsafeBalancesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BalancesServiceServer will
// result in compilation errors.
type UnsafeBalancesServiceServer interface {
	mustEmbedUnimplementedBalancesServiceServer()
}

func RegisterBalancesServiceServer(s grpc.ServiceRegistrar, srv BalancesServiceServer) {
	// If the following call pancis, it indicates UnimplementedBalancesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BalancesService_ServiceDesc, srv)
}

func _BalancesService_CurrentOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentOneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalancesServiceServer).CurrentOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalancesService_CurrentOne_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalancesServiceServer).CurrentOne(ctx, req.(*GetCurrentOneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BalancesService_ServiceDesc is the grpc.ServiceDesc for BalancesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BalancesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.BalancesService",
	HandlerType: (*BalancesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CurrentOne",
			Handler:    _BalancesService_CurrentOne_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "balances/grpc/balances.proto",
}
