// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: balances/grpc/balances.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCurrentOneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentOneRequest) Reset() {
	*x = GetCurrentOneRequest{}
	mi := &file_balances_grpc_balances_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentOneRequest) ProtoMessage() {}

func (x *GetCurrentOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balances_grpc_balances_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentOneRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentOneRequest) Descriptor() ([]byte, []int) {
	return file_balances_grpc_balances_proto_rawDescGZIP(), []int{0}
}

func (x *GetCurrentOneRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetCurrentOneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Balance       float64                `protobuf:"fixed64,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentOneResponse) Reset() {
	*x = GetCurrentOneResponse{}
	mi := &file_balances_grpc_balances_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentOneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentOneResponse) ProtoMessage() {}

func (x *GetCurrentOneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_balances_grpc_balances_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentOneResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentOneResponse) Descriptor() ([]byte, []int) {
	return file_balances_grpc_balances_proto_rawDescGZIP(), []int{1}
}

func (x *GetCurrentOneResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetCurrentOneResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

var File_balances_grpc_balances_proto protoreflect.FileDescriptor

const file_balances_grpc_balances_proto_rawDesc = "" +
	"\n" +
	"\x1cbalances/grpc/balances.proto\x12\x04grpc\"5\n" +
	"\x14GetCurrentOneRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"P\n" +
	"\x15GetCurrentOneResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x01R\abalance2X\n" +
	"\x0fBalancesService\x12E\n" +
	"\n" +
	"CurrentOne\x12\x1a.grpc.GetCurrentOneRequest\x1a\x1b.grpc.GetCurrentOneResponseB\x0fZ\rbalances/grpcb\x06proto3"

var (
	file_balances_grpc_balances_proto_rawDescOnce sync.Once
	file_balances_grpc_balances_proto_rawDescData []byte
)

func file_balances_grpc_balances_proto_rawDescGZIP() []byte {
	file_balances_grpc_balances_proto_rawDescOnce.Do(func() {
		file_balances_grpc_balances_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_balances_grpc_balances_proto_rawDesc), len(file_balances_grpc_balances_proto_rawDesc)))
	})
	return file_balances_grpc_balances_proto_rawDescData
}

var file_balances_grpc_balances_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_balances_grpc_balances_proto_goTypes = []any{
	(*GetCurrentOneRequest)(nil),  // 0: grpc.GetCurrentOneRequest
	(*GetCurrentOneResponse)(nil), // 1: grpc.GetCurrentOneResponse
}
var file_balances_grpc_balances_proto_depIdxs = []int32{
	0, // 0: grpc.BalancesService.CurrentOne:input_type -> grpc.GetCurrentOneRequest
	1, // 1: grpc.BalancesService.CurrentOne:output_type -> grpc.GetCurrentOneResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_balances_grpc_balances_proto_init() }
func file_balances_grpc_balances_proto_init() {
	if File_balances_grpc_balances_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_balances_grpc_balances_proto_rawDesc), len(file_balances_grpc_balances_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_balances_grpc_balances_proto_goTypes,
		DependencyIndexes: file_balances_grpc_balances_proto_depIdxs,
		MessageInfos:      file_balances_grpc_balances_proto_msgTypes,
	}.Build()
	File_balances_grpc_balances_proto = out.File
	file_balances_grpc_balances_proto_goTypes = nil
	file_balances_grpc_balances_proto_depIdxs = nil
}
